name: release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-windows:
    name: windows build
    runs-on: windows-latest
    steps:
      - name: Setup Windows 10 SDK version 10.0.20348.0
        uses: GuillaumeFalourd/setup-windows10-sdk-action@v1.8
        with:
          sdk-version: 20348
      - name: Install NSIS
        run: |
          iwr -useb get.scoop.sh -outfile 'install.ps1'
          .\install.ps1 -RunAsAdmin
          scoop update
          scoop bucket add extras
          scoop install xmake
      - name: pre-env
        shell: powershell
        run: |
          $env:path+=";$Home\scoop\shims"
          xmake update -s https://github.com/zeromake/xmake.git#master
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: build-x86_64
        env:
          VERSION: ${{ github.ref_name }}
        shell: powershell
        run: |
          $env:path+=";$Home\scoop\shims"
          xmake repo -a self https://github.com/zeromake/xrepo.git
          xmake f -c -y -vD
          xmake build -y onscripter
      - uses: actions/upload-artifact@v3
        with:
          name: onscripter-windows-${{ github.run_id }}
          path: |
            dist/onscripter-windows-x86_64.exe
  build-osx:
    name: macos build
    runs-on: macos-latest
    steps:
      - name: install-xmake
        run: |
          brew install xmake
          xmake --version
      - name: pre-env
        run: |
          xmake update -s https://github.com/zeromake/xmake.git#master
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: pre-repo
        run: |
          xmake repo -a self https://github.com/zeromake/xrepo.git
      - name: build-x64
        env:
          VERSION: ${{ github.ref_name }}
        run: |
          xmake f -c -y
          xmake build -y onscripter
      - name: build-arm64
        env:
          VERSION: ${{ github.ref_name }}
          ARCH: arm64
        run: |
          xmake f -a arm64 -c -y
          xmake build -y onscripter
      - uses: actions/upload-artifact@v3
        with:
          name: onscripter-osx-${{ github.run_id }}
          path: |
            dist/onscripter-darwin-x86_64
            dist/onscripter-darwin-arm64
  update-release:
    runs-on: ubuntu-latest
    needs: [build-osx, build-windows]
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: onscripter-windows-${{ github.run_id }}
          path: dist
      - uses: actions/download-artifact@v3
        with:
          name: onscripter-osx-${{ github.run_id }}
          path: dist
      - name: list file
        run: |
          ls -R
      - name: update
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            dist/onscripter-windows-x86_64.exe
            dist/onscripter-darwin-x86_64
            dist/onscripter-darwin-arm64
